---
sensor:
  - platform: template
    sensors:
      security_status:
        value_template: >-
          {% if is_state('binary_sensor.front_door', 'on') %}
            Door Opened
          {% elif is_state('group.motion', 'off')
          or is_state('binary_sensor.presence_owners', 'on') %}
            Safe
          {% else %}
            Unsafe
          {% endif %}
        icon_template:
          mdi:shield-home


input_boolean:
  security_show_more:
    initial: false


script:
  front_door_snapshot:
    sequence:
      - service: camera.snapshot
        data:
          entity_id: camera.front_door_live
          filename: /config/www/images/frontdoor.jpg
      - service: notify.all
        data:
          message: "Входная дверь открыта!"
          data:
            photo:
              file: /config/www/images/frontdoor.jpg
              caption: "Входная дверь открыта!"


automation:
  - alias: '[Security] Front Door Opened'
    initial_state: on
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_door
        to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.presence_owners
          state: 'off'
        - condition: state
          entity_id: group.sleeping_owners_all
          state: 'on'
    action:
      - service: script.front_door_snapshot
      - delay: 1
      - repeat:
          while:
            - condition: state
              entity_id: binary_sensor.front_door
              state: 'on'
          sequence:
            - service: script.front_door_snapshot
            - delay: 5

