title: Settings
icon: mdi:cogs
path: settings
panel: true
cards:
  - type: custom:layout-card
    layout_type: custom:horizontal-layout
    layout:
      max_cols: 3
    cards:
#      - type: custom:auto-entities
#        unique: true
#        card:
#          type: entities
#          head:
#            type: section
#            label: "Потребляемая мощность"
#        filter:
#          include:
#            - entity_id: sensor.daily_energy_consumption
#            - entity_id: sensor.monthly_energy_consumption
#            - entity_id: sensor.total_energy_consumption
#            - entity_id: "*.daily_energy_consumption_*"
#            - entity_id: "*.monthly_energy_consumption_*"
#            - entity_id: "*_power"
#      #     exclude:
#      #       - entity_id: "*_2"
#      #       - entity_id: "*_management"

#      - type: custom:layout-break
      - type: custom:auto-entities
        show_empty: false
        unique: true
        card:
          type: entities
          title: "Shelly need update"
          show_header_toggle: false
        filter:
          include:
            - entity_id: '*firmware_update*'

      - type: vertical-stack
        cards:
          - type: custom:auto-entities
            show_empty: false
            unique: true
            card:
              type: entities
              title: "Things that are probably broken"
              show_header_toggle: false
            filter:
              include:
                - state: "unknown"
                - state: "unavailable"
              exclude:
                - domain: group
                - domain: input_text
                - domain: history_graph
                - entity_id: "media_player.emby_*"

#      - type: custom:layout-break
      - type: custom:auto-entities
        show_empty: false
        unique: true
        card:
          type: entities
          title: "Батарейки"
          show_header_toggle: false
        filter:
          include:
            - group: group.battery_status
      - type: custom:auto-entities
        unique: true
        card:
          type: entities
          title: "Battery warning"
        filter:
          include:
            - group: group.battery_alert

#      - type: custom:layout-break
      - type: vertical-stack
        cards:
          - !include cards/zigbee.yaml
          - !include cards/links.yaml
          - !include cards/dev_content.yaml

