---
homeassistant:
  customize_glob:
    sensor.bedroom_*:
      friendly_name: "Спальня"
    binary_sensor.bedroom_*:
      friendly_name: "Спальня"


jq300:
  username: !secret jq300_username
  password: !secret jq300_password
  # devices: none
  # receive_tvoc_in_ppb: true
  # receive_hcho_in_ppb: true


iaquk:
  bedroom:
    sources:
      humidity: sensor.bedroom_humidity
      co2: sensor.bedroom_eco2
      tvoc: sensor.bedroom_tvoc
      hcho: sensor.bedroom_hcho
      pm: sensor.bedroom_pm25


media_player:
  - platform: androidtv
    name: Bedroom TV
    device_class: androidtv
    host: 192.168.1.82
    state_detection_rules:
      'com.plexapp.android':
        - 'paused':
            'media_session_state': 3  # this indentation is important!
            'wake_lock_size': 1       # this indentation is important!
        - 'playing':
            'media_session_state': 3  # this indentation is important!
        - 'standby'

