substitutions:
  device_name: "Kitchen"
  device_ip: 192.168.1.65
  
  <<: !include secrets.yaml

esphome:
  name: kitchen
  platform: ESP32
  board: nodemcu-32s

status_led:
  pin: GPIO2

wifi:
  ssid: $wifi_ssid
  password: !secret wifi_password
  domain: !secret network_domain

  manual_ip:
    static_ip: $device_ip
    gateway: !secret network_gateway
    subnet: !secret network_mask

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: !secret ota_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

i2c:
  - id: bus_indoor
    sda: 21
    scl: 22
    scan: True
  - id: bus_outdoor
    sda: 19
    scl: 23
    scan: True

binary_sensor:
  - platform: gpio
    pin: 18
    name: "${device_name} Motion"
    device_class: motion

sensor:
  - platform: uptime
    name: "${device_name} Uptime"
    id: device_uptime

  - platform: template
    name: "Pressure mmHg"
    id: pressure_mmhg
    unit_of_measurement: mmHg
    icon: mdi:gauge

  # Outdoor sensors ####################################################

  - platform: htu21d
    i2c_id: bus_outdoor
    # address: 0x40
    update_interval: 60s
    temperature:
      name: "Outdoor Temperature"
      id: outdoor_temp
    humidity:
      name: "Outdoor Humidity"
      id: outdoor_humi

  - platform: bmp085
    i2c_id: bus_outdoor
    address: 0x77
    update_interval: 60s
    temperature:
      name: "Outdoor Temperature 2"
    pressure:
      name: "Pressure"
      id: pressure_hpa
      on_value:
        then:
          - sensor.template.publish:
              id: pressure_mmhg
              state: !lambda 'return x / 1.33322;'

  - platform: bh1750
    i2c_id: bus_outdoor
    address: 0x23
    update_interval: 60s
    name: "Outdoor Illuminance"

  # Indoor sensors ####################################################

  - platform: bmp280
    i2c_id: bus_indoor
    address: 0x76
    update_interval: 60s
    temperature:
      name: "${device_name} Temperature"
      oversampling: 16x
      id: indoor_temp
    pressure:
      name: "Pressure 2"

  # - platform: hdc1080
  #   i2c_id: bus_indoor
  #   # address: 0x40
  #   update_interval: 60s
  #   humidity:
  #     name: "${device_name} Humidity"
  #     id: indoor_humi

  - platform: ccs811
    i2c_id: bus_indoor
    address: 0x5A
    update_interval: 60s
    temperature: indoor_temp
    # humidity: indoor_humi
    # baseline: 
    eco2:
      name: "${device_name} eCO2"
      id: indoor_eco2
      filters:
        - lambda: |-
            if (x >= 400 && x <= 8192) {
              return x;
            } else {
              return {};
            }
    tvoc:
      name: "${device_name} tVOC PPB"
      id: indoor_tvoc_ppb
      filters:
        - lambda: |-
            if (x >= 0 && x <= 1187 && id(indoor_eco2).state >= 400) {
              return x;
            } else {
              return {};
            }
      on_value:
        then:
          - sensor.template.publish:
              id: indoor_tvoc_mgm3
              # state: !lambda 'return (x * 56.106) / (24.45 * 1000);'
              state: !lambda 'return (x * 8.3126 * (273 + id(indoor_temp).state)) / (56.106 * id(pressure_hpa).state * 100);'

  - platform: template
    name: "${device_name} tVOC"
    id: indoor_tvoc_mgm3
    unit_of_measurement: "mg/m³"
    accuracy_decimals: 3
    icon: mdi:radiator
