---
homeassistant:
  customize_glob:
    device_tracker.*_bt:
      source_type: bluetooth
    sensor.*_bt:
      source_type: bluetooth

    binary_sensor.*_motion:
      device_class: motion
    binary_sensor.*_occupancy:
      device_class: motion
    binary_sensor.everyone_is_asleep:
      icon: mdi:sleep


group:
  motion:
    name: "Движение в доме"
    all: false
    entities:
      - binary_sensor.front_door
      - binary_sensor.hallway_motion
      - binary_sensor.kitchen_motion
      - binary_sensor.bedroom_motion
      - binary_sensor.living_room_motion
  motion_public:
    name: "Движение в общих зонах"
    all: false
    entities:
      - binary_sensor.front_door
      - binary_sensor.hallway_motion
      - binary_sensor.kitchen_motion
      - binary_sensor.living_room_motion


binary_sensor:
  - platform: mqtt
    name: Monitor Hallway
    state_topic: 'presence/hallway/status'
    payload_on: "online"
    payload_off: "offline"

  - platform: mqtt
    name: Monitor Bedroom
    state_topic: 'presence/bedroom/status'
    payload_on: "online"
    payload_off: "offline"

  - platform: template
    sensors:
      presence_owners:
        friendly_name: "Хозяева в Доме"
        device_class: presence
        value_template: >-
          {{ is_state('person.limych', 'home') }}

      presence:
        friendly_name: "Люди в Доме"
        device_class: presence
        value_template: >-
          {{ is_state('binary_sensor.presence_owners', 'on')
          or is_state('input_boolean.guest_mode', 'on')
          or is_state('group.motion', 'on') }}
          
  - platform: bayesian
    name: Everyone Is Asleep
    probability_threshold: 0.95
    prior: 0.42
    observations:
      - platform: state
        entity_id: sun.sun
        to_state: below_horizon
        prob_given_true: 0.75
      - platform: state
        entity_id: sensor.system_media_bedroom_tv
        to_state: "Offline"
        prob_given_true: 0.65
      - platform: template
        value_template: >-
          {{ is_state('group.motion', 'off')
          and states.group.motion.last_changed > states.group.motion_public.last_changed }}
        prob_given_true: 0.85


input_boolean:
  everyone_is_asleep:
    name: "Все жители спят"
    icon: mdi:sleep


automation:
  - alias: '[Presence] Initialize on Hass Started'
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: mqtt.publish
        data:
          topic: "presence/scan/restart"

  - alias: '[Presence] Owners presence On'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_owners
        to: 'on'
    condition:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(states('sensor.uptime'))) >= 2 }}"
    action:
      - service: notify.limych
        data_template:
          message: "Добро пожаловать домой!"

  - alias: '[Presence] Owners presence Off'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.presence_owners
        to: 'off'
    condition:
      - condition: template
        value_template: "{{ (as_timestamp(now()) - as_timestamp(states('sensor.uptime'))) >= 2 }}"
    action:
      - service: notify.limych
        data_template:
          message: "Счастливого пути!"

  - alias: '[Presence] Everyone is Asleep'
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.everyone_is_asleep
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.everyone_is_asleep

  - alias: '[Presence] Someone are Awake'
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.motion_public
        to: 'on'
    condition:
      - condition: state
        entity_id: input_select.day_mode
        state: 'Утро'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.everyone_is_asleep
      # - service: notify.all
      #   data:
      #     message: 'С добрым утром!'

