---
homeassistant:
  customize_glob:
    sensor.*battery*:
      unit_of_measurement: '%'
      templates:
        hs_color: >-
          if (state > 50) return [0, 0];
          else if (state > 25) return [40, 70];
          else return [0, 85];
    sensor.*_pc_*:
      icon: mdi:laptop
      templates:
        hs_color: >-
          if (state === 'Online') return [0, 0];
          else if (state === 'Offline') return [0, 85];
          else return [40, 70];

