---
homeassistant:
  customize_glob:
    sensor.*battery*:
      templates:
        icon_color: |-
          if (state > 75) return 'hsl(100, 100%, 50%)'
          else if (state > 50) return 'hsl(60, 100%, 50%)'
          else if (state > 25) return 'hsl(35, 100%, 50%)'
          else if (state <= 25) return 'hsl(0, 100%, 50%)'
          else return 'var(--disabled-text-color)'

    sensor.*_pc_*:
      icon: mdi:laptop
      templates:
        icon_color: |-
          if (state === 'Online') return 'var(--paper-item-icon-color)'
          else return 'var(--disabled-text-color)'

