---
homeassistant:
  customize:
    binary_sensor.internet:
      friendly_name: "Интернет"
      templates:
        icon_color: |-
          if (state === 'on') return 'var(--paper-item-icon-color)'
          else return 'var(--accent-color)'


sensor:
  - platform: dnsip


binary_sensor:
  - platform: ping
    name: internet
    host: yandex.ru
    scan_interval: 10
    count: 3


speedtestdotnet:
  scan_interval:
    hours: 3

